### ISSUE TITLE
Using state parameter with End User Authorization?

### ISSUE THREAD

**Issue by jcope2013** [cronofy/omniauth-cronofy#7]
when trying to pass a state parameter to /auth/cronofy?state=test, I have no access to the state parameter inside my omniauth callback in ``` request.env['omniauth.auth'] ```, is there a way to get it?

https://www.cronofy.com/developers/api/#request-authorization-state

**Comment by atainton** [comment]
@jcope2013 what did you end up doing, I have run into the same issue.
